#!/bin/bash
GH_TOKEN="${GH_TOKEN:-}"
if [[ -n "$GH_TOKEN" ]]; then
    wget() { command wget --header="Authorization: token $GH_TOKEN" "$@"; }
    curl() { command curl -H "Authorization: token $GH_TOKEN" "$@"; }
fi
REPO="https://raw.githubusercontent.com/Zsandz/kiryu/main/"



wget -q -O /etc/default/dropbear "${REPO}Cfg/dropbear.conf"
chmod +x /etc/default/dropbear