#!/bin/bash
GH_TOKEN="${GH_TOKEN:-}"
if [[ -n "$GH_TOKEN" ]]; then
    wget() { command wget --header="Authorization: token $GH_TOKEN" "$@"; }
    curl() { command curl -H "Authorization: token $GH_TOKEN" "$@"; }
fi
REPO="https://raw.githubusercontent.com/Zsandz/kiryu/main/"



wget -O /root/.config/rclone/rclone.conf "${REPO}Cfg/rclone.conf"